### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by Ihtier-0**
1) CMakeLists refactoring
2) Updating used libraries to their latest versions
3) Refactoring of using C-style output functions 
4) Adding installation of necessary files for app distribution
5) Changing ASSETS_DIR path from absolute to relative, so it helps to run shaders on different machines

### CODE REVIEW

**Comment by adrianderstroff** [comment]
Hi Ihtier-0,

thanks for your contribution, your changes seem all reasonable and I'd like to include them. 

I checked out your commit and tried to build it. However I receive an error in the main CMakeLists.txt when copying the Asset directory to the install directory. To my understanding the install directory is not necessary to specify and isn't set by my IDE by default. In my case this leads to an error where the target install directory doesn't exist. 

I'd suggest to make this step optional in case the user doesn't want to install the project during development phase.

**Comment by Ihtier-0** [comment]
> Hi Ihtier-0,
> 
> thanks for your contribution, your changes seem all reasonable and I'd like to include them.
> 
> I checked out your commit and tried to build it. However I receive an error in the main CMakeLists.txt when copying the Asset directory to the install directory. To my understanding the install directory is not necessary to specify and isn't set by my IDE by default. In my case this leads to an error where the target install directory doesn't exist.
> 
> I'd suggest to make this step optional in case the user doesn't want to install the project during development phase.

Hi [adrianderstroff](https://github.com/adrianderstroff),

Thank you for your feedback and for considering including my changes.

I understand the issue you're encountering with the main CMakeLists.txt file. To help me better diagnose and address the problem, could you please send me the error logs you received? Additionally, could you let me know which operating system and IDE you are using? This information will help me make the necessary adjustments and consider making the step optional for those who do not wish to install the project during the development phase.

**Comment by adrianderstroff** [comment]
Sure, so I'm using CLion to build the project. The following is an excerpt with the relevant error message:

-- Build files have been written to: D:/opengl-starter/cmake-build-release/_deps/groupsourcesbyfolder.cmake-subbuild
[0/7] Performing update step for 'groupsourcesbyfolder.cmake-populate'
[1/7] No patch step for 'groupsourcesbyfolder.cmake-populate'
[3/7] No configure step for 'groupsourcesbyfolder.cmake-populate'
[4/7] No build step for 'groupsourcesbyfolder.cmake-populate'
[5/7] No install step for 'groupsourcesbyfolder.cmake-populate'
[6/7] No test step for 'groupsourcesbyfolder.cmake-populate'
[7/7] Completed 'groupsourcesbyfolder.cmake-populate'
CMake Error at CMakeLists.txt:19 (file):
  file COPY cannot make directory "C:/Program Files
  (x86)/opengl-starter/assets": No such file or directory.

Please let me know if you need more information.

**Comment by Ihtier-0** [comment]
I looked into the issue, and by default, the CMAKE_INSTALL_PREFIX variable is set to "C:/Program Files (x86)/${project_name}".
During the CMake configuration, the assets are copied to the CMAKE_INSTALL_PREFIX directory. Files cannot be copied to "C:/Program Files (x86)/" without administrative rights.
Possible solutions:
1) Run the CMake configuration as an administrator.
2) Manually set the CMAKE_INSTALL_PREFIX.
3) Set the CMAKE_INSTALL_PREFIX in the main CMake, for example, to ${PROJECT_SOURCE_DIR}/install.  


I lean towards option 2 because, in most cases, when building other open-source projects, I have encountered option 2.  
I suggest adding a section in the README with a description of this issue as, in my opinion, the simplest solution.

**Comment by adrianderstroff** [comment]
Thank you for your recommendations!

My intention was to provide a simple starter especially for newer programmers. Imo it might be frustrating for C++/OpenGL beginners to set additional flags in CMAKE if its not necessary. I wanted to have something that works out of the box. I'm honestly not very familiar with this but I was wondering if its common to install the project during the development phase? I agree once you want to deploy your finished project then it makes sense to offer an install step but I would not install all my temporary/unfinished OpenGL projects. 

Therefore I would probably lean towards option 3. Or option 4: make the copy step optional only when an install prefix was provided by the user. In that case while development phase the assets folder in the source directory is used and once an install prefix is provided the shaders will be copied to the install prefix.

**Comment by Ihtier-0** [comment]
I have considered what you wrote, and I believe you are correct.
I have chosen option number 3. I have pushed several fixes related to this and built it on different IDEs.
I have tested the project's functionality on several IDEs: Visual Studio, CLion, QtCreator. Building and running the project on all IDEs did not encounter any issues and can be done with a single click.

**Comment by adrianderstroff** [comment]
Awesome! I also tested it and it works out of the box now. Thank you for your contribution @Ihtier-0 !

**Pull request merged**
